services:
  postgres:
    container_name: spring-postgres
    image: postgres
    environment:
      POSTGRES_USER: huichihwang
      POSTGRES_PASSWORD: taya30621
      POSTGRES_DB: login_auth
    ports:
      - "5432:5432"
    volumes:
      - db-data:/data/postgres
    restart: unless-stopped

  maildev:
    container_name: spring-maildev
    image: maildev/maildev
    ports:
      - "1025:1025"
      - "1080:1080"
    restart: unless-stopped

volumes:
  db-data: